### PR TITLE
[DO-NOT-MERGE] Disable the gem for easy removal

### PR DESCRIPTION
**Pull request by jewilmeer**
This should indicate all places where the gem is called. As the calls are not that obvious `open`.

This is ment as a utility to make it easier to remove the occurrences of open in convert-workflow: https://trello.com/c/NJmmhNyL/677-13-upgrade-convert-workflow-to-the-latest-ruby

### CODE REVIEW

**Review by koenrh — APPROVED** [review]

**Comment by jewilmeer** [comment]
Tnx @koenrh, this wasn't ment to be merged, but just a tool to make https://trello.com/c/NJmmhNyL/677-13-upgrade-convert-workflow-to-the-latest-ruby easier.

**Comment by eterps** [comment]
Hey guys :wave:

**Comment by jurre** [comment]
Hi Erik 😄 👋

**Comment by koenbollen** [comment]
Hey! 👋

**Pull request closed without merging**
