### PR TITLE
Update AWS SDK to version 3

### PR DESCRIPTION
**Pull request by koenrh**
This gem, as a dependency of 'blendle-content', is currently preventing us from applying a security update ('nokogiri') to one of our projects. The problem is that this gem requires a legacy version (version 1) of AWS SDK, which pins 'nokogiri' to version 1 (where version 2 is the latest).

A few remarks:
- It's no longer needed to explicitly disable SSL (e.g. for testing). That is now determined based on the passed URI (e.g. `http://` means no SSL).
- `AWS_S3_ENDPOINT` should now be a fully qualified URI, according to the AWS SDK change log:

>:endpoint must now be a fully qualified HTTP or HTTPS uri instead of a hostname.

To be honest, I would rather get rid of using this gem altogether, but I thought it would be easier for now to just make sure it works with AWS SDK version 3.

What do you think, @jewilmeer?

### CODE REVIEW

**Comment by jewilmeer** [comment]
I'll test if the returned object still is a IO object. In aws-sdk-v2 this wasn't the case, making an upgrade nearly impossible.

**Comment by jewilmeer** [comment]
Writing to the file stream is still broken. Maybe we should just try to fetch and replace the use cases. It's mostly used in convert_workflow
```
open('s3://static-test.blendle.nl/test.json', 'w') { |f| f.write 'henk' }
Aws::S3::Errors::NoSuchKey: The specified key does not exist.
from /Users/jan-willemvandermeer/.gem/ruby/2.4.1/gems/aws-sdk-core-3.7.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
```

**Comment by koenrh** [comment]
```ruby
object = bucket.object(key).get.body
```

An object's `#get` method returns an object of type `Aws::S3::Types::GetObjectOutput`, which has a method `#body` that returns an `IO` object.

See: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Types/GetObjectOutput.html#body-instance_method

**Comment by koenrh** [comment]
Ah, I see. Yeah, this breaks writing, because the API of S3 SDK has changed drastically.

**Comment by koenrh** [comment]
```ruby
if block_given?
  yield object
else
  object
end
```

We could probably work around this by assuming (in case of a block) to always return a writable S3 object (on which you can call [put](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Object.html#put-instance_method))? 

https://github.com/blendle/open-uri-s3/pull/3/files#diff-923e43e93bf42ef7eb438d038930d635R26

**Comment by jewilmeer** [comment]
that would be confusing, because the whole purpose is to mimic the open-uri api. Would be better to refactor the write actions to not use open-uri-s3 at all.

If you would rewrite it to put, you'll need to do this: `{|file| file.put(body: 'my body'}`

**Comment by eterps** [comment]
Yes, originally the idea was to be compatible with the open-uri API:

selection_417

We could make a wrapper object that 'quacks' like IO instead of using the V3 response object directly.

**Comment by eterps** [comment]
> Would be better to refactor the write actions to not use open-uri-s3 at all.

Let me know if that would be the course of action, otherwise I'll see if I can make it compatible with AWS SDK version 3 and `IO`.

**Comment by koenrh** [comment]
@eterps I think I would prefer to make 'open-uri-s3' compatible with AWS SDK version 3 so that we don't have to make any changes (other than updating this gem) to projects that depend on this gem.

**Comment by eterps** [comment]
Ok, I have put in my list :+1:

**Comment by jewilmeer** [comment]
Erik, I’m happy to assist with this

Op wo 15 nov. 2017 om 09:49 schreef Erik Terpstra <notifications@github.com

**Pull request closed without merging**
